import os


CORE_DIRECTORY = os.environ["GAME_ENGINE_CORE_DIRECTORY"] if "GAME_ENGINE_CORE_DIRECTORY" in os.environ else "."
TIMEOUT_SECONDS = 1
CUMULATIVE_TIMEOUT_SECONDS = 6
MAX_CHARACTERS_READ = 4096
READ_CHUNK_SIZE = 1024